eternal-tools:
  - id: 1
    name: "§f✦ §c§lÉpée de Zeus §f✦"
    Material: "DIAMOND_SWORD"
    Lore:
      - ""
      - "§cRareté: §6✭✭✭✭✭"
      - ""
      - "§7Cette épée ne peut jamais être perdue !"
      - ""
    Enchantments:
      - enchantment: "DAMAGE_ALL"
        level: 5
      - enchantment: "FIRE_ASPECT"
        level: 2
    Unbreakable: true
  - id: 2
    name: "§fArc Éternel"
    Material: "BOW"
    Lore:
      - ""
      - "§cRareté: §6✭✭✭✭✭"
      - ""
      - "§7Cet arc ne peut jamais être perdu !"
      - ""
    Enchantments:
      - enchantment: "FLAME"
        level: 1
      - enchantment: "PUNCH"
        level: 2
      - enchantment: "ARROW_INFINITE"
        level: 1
    Unbreakable: true
  - id: 3
    name: "§fPelle Éternelle"
    Material: "DIAMOND_SHOVEL"
    Lore:
      - ""
      - "§cRareté: §6✭✭✭✭✭"
      - ""
      - "§7Cette pelle ne peut jamais être perdue !"
      - ""
    Enchantments:
      - enchantment: "EFFICIENCY"
        level: 5
    Unbreakable: true
  - id: 4
    name: "§fHache Éternelle"
    Material: "DIAMOND_AXE"
    Lore:
      - ""
      - "§cRareté: §6✭✭✭✭✭"
      - ""
      - "§7Cette hache ne peut jamais être perdue !"
      - ""
    Enchantments:
      - enchantment: "EFFICIENCY"
        level: 5
    Unbreakable: true

permission-messages:
  default: "§cVous n'avez pas la permission d'utiliser cette commande."
